 1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Print the numpy version and the configuration

In [15]:
import numpy as np
print(np._version_)
print(np.show_config())

AttributeError: module 'numpy' has no attribute '_version_'

3. Create a null vector of size 10

In [16]:
x = np.zeros(10)
print(x)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


4. How to find the memory size of any array

In [19]:
print("{} bytes".format(x.size * x.itemsize))

80 bytes


5. Create a null vector of size 10 but the fifth value which is 1

In [3]:
x = np.zeros(10)
x[5] = 1
print(x)

[ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]


6. Create a vector with values ranging from 10 to 49

In [6]:
x = np.array(range(10,50))
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


7. Reverse a vector (first element becomes last)

In [10]:
x = x[::-1]
print(x)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


8. Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


9. Create a 3x3 identity matrix

In [12]:
x = np.identity(3)
print(x)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


10. Create a 3x3x3 array with random values

In [17]:
x = np.random.random((3,3))
print(x)

[[ 0.27798687  0.07967985  0.28456748]
 [ 0.40319418  0.42179997  0.01980613]
 [ 0.81580297  0.33918655  0.84291986]]


11. Create a 10x10 array with random values and find the minimum and maximum values

In [18]:
x = np.random.random((10,10))
min = x.min()
max = x.max()
print(x)
print(min)
print(max)

[[ 0.19210651  0.99986529  0.42982114  0.28082023  0.7333947   0.48381239
   0.19164692  0.83587123  0.91967607  0.71009277]
 [ 0.9941259   0.08138714  0.32992523  0.07719905  0.94516288  0.70040808
   0.71307728  0.48276045  0.85673424  0.91624993]
 [ 0.15911714  0.67998983  0.03847379  0.32962821  0.70076041  0.49056457
   0.50061178  0.50855575  0.8950021   0.49466916]
 [ 0.35808096  0.77280383  0.70537579  0.37933569  0.4364798   0.21678817
   0.98266062  0.19078391  0.5141654   0.74832073]
 [ 0.65401581  0.88710619  0.93660366  0.65451359  0.78649047  0.57661108
   0.17081957  0.97162672  0.9582148   0.271022  ]
 [ 0.18940624  0.2390906   0.68280378  0.37358119  0.13873483  0.21946315
   0.98325477  0.25349165  0.94308026  0.84137908]
 [ 0.9065647   0.50658004  0.72546904  0.94885007  0.8913951   0.69146857
   0.16777483  0.24985645  0.75356708  0.42405211]
 [ 0.16807538  0.22572591  0.4592251   0.37237086  0.57931851  0.36882886
   0.83006594  0.90277158  0.28863653  0.5863329 ]


12. Create a random vector of size 30 and find the mean value

In [21]:
x = np.random.random(30)
print(x)
mean = np.mean(x)
print(mean)

[ 0.28042757  0.90142221  0.02857687  0.05570871  0.67340772  0.2001071
  0.5097259   0.3721183   0.34869768  0.08611539  0.36067891  0.13951889
  0.5050992   0.75863167  0.24945012  0.07770061  0.74653051  0.09581486
  0.90617098  0.30605965  0.57215876  0.93397165  0.93403547  0.42293644
  0.18892331  0.8818019   0.01575843  0.33271153  0.71398534  0.79212728]
0.446345764779


13. Create a 2d array with 1 on the border and 0 inside

In [22]:
x = np.ones((5,5))
x[1:-1,1:-1] = 0
print(x)

[[ 1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.]]


14. How to add a border (filled with 0’s) around an existing array?

In [26]:
x = np.ones((5,5))
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


15. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [27]:
x = np.diag(1+np.arange(4), k = -1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


16. Normalize a 5x5 random matrix

In [33]:
x= np.random.random((3,3))
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print(x)

[[ 0.23708091  0.42296853  0.79078051]
 [ 0.80804662  0.81163134  0.21653344]
 [ 0.75873074  0.09473833  0.6637266 ]]
[[ 0.19855485  0.45785103  0.97091501]
 [ 0.99499964  1.          0.169893  ]
 [ 0.92620852  0.          0.79368646]]


17. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [37]:
x = np.random.random((5,3))
y = np.random.random((3,2))
z = np.dot(x, y)

print("first matrix is \n {} \n second matrix is \n {} \n The dot product is \n {}".format(x,y,z))

first matrix is 
 [[ 0.73191892  0.40948143  0.02716474]
 [ 0.9256436   0.6674069   0.30052948]
 [ 0.81269133  0.1112283   0.41016151]
 [ 0.33090462  0.31507521  0.95244441]
 [ 0.85625735  0.91790309  0.4073289 ]] 
 second matrix is 
 [[ 0.23576708  0.11732547]
 [ 0.55047538  0.42823039]
 [ 0.26922387  0.74912603]] 
 The dot product is 
 [[ 0.40528523  0.28157494]
 [ 0.66653707  0.61953995]
 [ 0.36325957  0.45024339]
 [ 0.50787833  0.88724922]
 [ 0.81682301  0.79867548]]


18. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [51]:
a = np.arange(11)
m = (a > 2) & (a < 8)
a[m] *= -1
print(a)

[ 0  1  2 -3 -4 -5 -6 -7  8  9 10]


19. What is the output of the following script? \
print(sum(range(5),-1))\
from numpy import *\
print(sum(range(5),-1))

In [52]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


20. How to find common values between two arrays?

In [53]:
array1 = np.array([0, 1, 2, 4, 6, 8, 13, 17])
array2 = [1, 3, 4, 15, 17]
x = np.intersect1d(array1, array2)
print(x)

[ 1  4 17]


21. Is the following expressions true? np.sqrt(-1) == np.emath.sqrt(-1)

In [54]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

22. Create a 5x5 matrix with row values ranging from 0 to 4

In [55]:
x = np.zeros((5,5))
x += np.arange(5)
print(x)

[[ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]]


23. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [58]:
x =  np.linspace(0,1,12,endpoint=True)[1:-1]
print(x)

[ 0.09090909  0.18181818  0.27272727  0.36363636  0.45454545  0.54545455
  0.63636364  0.72727273  0.81818182  0.90909091]


24. Create a random vector of size 10 and sort it

In [61]:
x = x = np.random.random(10)
print(x)
x.sort()
print(x)

[ 0.09548627  0.35488278  0.34387142  0.51365793  0.25472887  0.33834147
  0.80987436  0.35652825  0.39644613  0.9483035 ]
[ 0.09548627  0.25472887  0.33834147  0.34387142  0.35488278  0.35652825
  0.39644613  0.51365793  0.80987436  0.9483035 ]


25. Consider two random array A and B, check if they are equal

In [71]:
A = np.random.randint(0,2,6)
print("the first array is: {}".format(A))
B = np.random.randint(0,2,6)
print("the second array is: {}".format(B))
array_equal = np.allclose(A, B)
print(array_equal)

the first array is: [0 0 1 1 0 1]
the second array is: [0 0 1 1 0 1]
True
